name: Testes Unitários
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Instalar dependências
        run: npm install

      - name: Executar testes
        id: test
        run: npm test

      - name: Notificar sucesso
        if: success()  # Este passo será executado apenas se os testes passarem
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "✅ Todos os testes passaram no repositório <nome-do-repositorio> em pull request #${{ github.event.pull_request.number }}. Ótimo trabalho!"
          }' YOUR_SLACK_WEBHOOK_URL

      - name: Notificar falha
        if: failure()  # Este passo será executado apenas se os testes falharem
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "🚨 Os testes falharam no repositório <nome-do-repositorio> em pull request #${{ github.event.pull_request.number }}. Confira os logs para mais detalhes."
          }' YOUR_SLACK_WEBHOOK_URL

